### ISSUE TITLE
Missing `bayes_opt.py` script?

### ISSUE THREAD

**Issue by miguelgondu** [AndySAnker/ScattBO#3]
Hi Andy,

I'm looking at the `bayes_opt` notebook. If I understand it correctly, it's importing stuff from an adjacent file called `bayes_opt.py`, but it seems to be missing. Or is `bayes_opt` a Python package you're installing?

Cheers,
Miguel.

**Comment by AndySAnker** [comment]
Hi Miguel,

bayes_opt is this module: https://pypi.org/project/bayesian-optimization/

**Comment by miguelgondu** [comment]
Cool! I wonder what they do inside that library. Thanks!
